# Dockerfile

FROM python:3

# Add any additional dependencies if needed
RUN pip install dbt

# Copy your code into the container
COPY . /app

# Set the working directory
WORKDIR /app

# Run any necessary commands
CMD ["python", "your_script.py"]